### ISSUE TITLE
Inventory Filtering

### ISSUE THREAD

**Issue by melchin** [melchin/project#10]
We need to add the functionality where we can filter the movies in the inventory. We should be able to sort by different columns, and have a search bar that eliminates items from the list as each matching character is typed. In order to do this, we will need to keep some kind of data structure that stores our entire inventory. 

Clicking headings will sort by their column.
spinbox beside search bar to specifiy what you are searching by.

**Comment by melchin** [comment]
http://www.codeprogress.com/cpp/libraries/qt/showQtExample.php?key=QTableWidgetSortByColumnHeaderDoubleClick&index=523

**Comment by 8BitBadass** [comment]
header filtering working

**Comment by 8BitBadass** [comment]
all done $ merged into dev
