### ISSUE TITLE
Inventory Doesn't show When 'Next' button is pressed from Welcome Window

### ISSUE THREAD

**Issue by melchin** [melchin/project#3]
I moved some data members around. The Qtablewidgetitems are in the .h now... you can move them out of the .h as I was just playing around with things. I was able to get it to compile, but when I click on the next button, it does not show the table. We should maybe test to make sure that when an `Inventory` object is created, that the cells in that first row are what we expect, even though they do not show up on the window.

**Comment by 8BitBadass** [comment]
solved
