### ISSUE TITLE
dummy payment info.

### ISSUE THREAD

**Issue by 8BitBadass** [melchin/project#33]
add a dropdown in the combobox that saids "select payment info" and do not display anything until a method is chosen.

**Comment by melchin** [comment]
Do we not already have this? It's just defaulted to credit card.

**Comment by 8BitBadass** [comment]
i will add that today

**Comment by melchin** [comment]
No. We need to discuss this. I don't see the issue here.

**Comment by 8BitBadass** [comment]
just something that says choose method and until something is selected,
nothing else is shown

**Comment by melchin** [comment]
You may not want to do this. Since we are using layouts, if you hide the defaulted credit card stuff, the select a payment will appear at the bottom of the page. I could be wrong. But I tried something similar.

**Comment by 8BitBadass** [comment]
ok you can close it then
