### ISSUE TITLE
MAKE IT PRETTY

### ISSUE THREAD

**Issue by melchin** [melchin/project#47]
* [x] Everything aligns well.
* [x] Button sizes are acceptable.
* [x] Colors are helpful. Not distracting.
* [x] Text boxes are sized in a way to hint to users how much input is necessary. For example, the credit card number textbox should only be wide enough to fit 16 characters. This is the biggest issue we have, and I don't know an easy fix.  
* [x] make windows modal
* [x] make sure constraints work
* [x] nothing explodes
* [x] added sources for pics
* [x] checkout window looks decent enough.

**Comment by melchin** [comment]
Please use the checkboxes above.

**Comment by 8BitBadass** [comment]
popup dialogs are modal now and must be interacted with.
